<?
class m_stats_head extends IModuleHead{
	public $module_name = 'stats';
	public $module_title = 'Статистика';
	var $rights=array(
		'stats'=>array("Статистика", 'r,report,vip_report,voip_recognition,sale_channel_report','просмотр,отчет,vip report,телефония-нераспознаные,региональные представители'),
	);
	var $actions=array(
		'default'			=> array('stats','r'),
		'internet'			=> array('stats','r'),
		'ppp'				=> array('stats','r'),
		'voip'				=> array('stats','r'),
		'callback'			=> array('stats','r'),
		'vpn'				=> array('stats','r'),
		'send_view'			=> array('stats','report'),
		'send_process'		=> array('stats','report'),
		'send_add'			=> array('stats','report'),
		'report'			=> array('stats','report'),
		'report_traff_less'	=> array('stats','report'),
		'report_sms_gate'	=> array('stats','report'),
		'report_voip_e164_free' => array('stats','report'),
		'voip_sell'			=> array('stats','test'),
		'report_services'	=> array('stats','report'),
		'report_wimax'		=> array('stats','report'),
		'report_netbynet'	=> array('stats','report'),
		'report_onlime'	    => array('stats','report'),
		'report_onlime2'	    => array('stats','report'),
		'report_onlime_all'	    => array('stats','report'),
		'report_inn'	    => array('stats','report'),
		//'report_wimax_test'		=> array('stats','report'),
		'courier_sms'		=> array('stats','report'),
		'report_voip_operators_traf' => array('stats','vip_report'),
		'voip_free_stat' => array('stats','report'),
//		'recalcalls'		=> array('stats','modify'),
		'support_efficiency'	=>  array('stats','report'),
		'report_phone_sales'  =>  array('stats','report'),
		'report_agent' => array('stats','report'),
		'report_sale_channel' => array('stats','sale_channel_report'),
		'report_vpbx_stat_space' => array('stats', 'report'),
		'phone_sales_details' => array('stats','report')
        'agent_settings' => array('stats', 'vip_report'),
        'save_agent_settings' => array('stats', 'vip_report'),
	);
	var $menu=array(
		array('Интернет',		'internet'),
		array('Collocation',	'internet','&is_coll=1'),
		array('PPP',			'ppp'),
		array('Телефония',		'voip'),
		array('Состояние номеров',		'voip_free_stat'),
//		array('Пересчитать звонки','recalcalls'),
		array('Телефония прод.','voip_sell'),
		array('Callback',		'callback'),
		array('VPN',			'vpn'),
		array('Рассылка',		'send_view'),
		array('Отчёт',			'report'),
		array('Отчёт по мин. трафику',	'report_traff_less'),
		array('Свободные номера', 'report_voip_e164_free'),
		array('SMS Gate',		'report_sms_gate'),
		array('Отчет по услугам', 'report_services'),
		array('Отчет по WiMax', 'report_wimax'),
		//array('Отчет по WiMax (test)', 'report_wimax_test'),
		array('Отчет по Курьерам(SMS)', 'courier_sms'),
		array('Отчет по ТехПоддержке', 'support_efficiency'),
		array('Отчет по NetByNet', 'report_netbynet'),
		array('Отчет по OnLime', 'report_onlime'),
		array('Отчет по OnLime2', 'report_onlime2'),
		array('Отчет по OnLime 1+2', 'report_onlime_all'),
		array('Отчет: Продажи номеров', 'report_phone_sales'),

		array('Отчет: ИНН', 'report_inn'),
		array('Отчет по Агентам', 'report_agent'),
        array('Настройка Агента', 'agent_settings'),
		array('Региональные представители', 'report_sale_channel'),
		array('ВАТС: свободное про-во', 'report_vpbx_stat_space'),
	);
}
?>
