<?php

namespace app\modules\nnp\commands;

use app\modules\nnp\models\Country;
use yii\web\NotFoundHttpException;

/**
 * <list>
 * <list_item><phone_number>19191080</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:25</update_ts></list_item>
 * <list_item><phone_number>19191081</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191082</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191083</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191084</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191085</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191086</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191087</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191088</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 * <list_item><phone_number>19191089</phone_number><equipment>001</equipment><valid_from>2016-07-07 20:00:00</valid_from><valid_until></valid_until><actual_provi
 * der>602</actual_provider><previous_provider>941</previous_provider><block_owner>941</block_owner><update_ts>2016-07-07 12:00:26</update_ts></list_item>
 */
class PortedHungaryController extends PortedController
{
    /*
    private array $_operators = [
        '602' => 'GREENCOM (602)',
        '605' => 'H1 KOMM (605)',
        '606' => 'COMNICA (606)',
        '607' => 'RAYSTORM (607)',
        '608' => 'REBELL (608)',
        '609' => 'HBCOM (609)',
        '611' => 'MCNTELECOM (611)',
        '612' => 'GELKA (612)',
        '613' => 'FUREDKABEL (613)',
        '614' => 'NFON (614)',
        '615' => 'DIALOGA (615)',
        '616' => 'MEDVECZKY (616)',
        '618' => 'KIS FAL (618)',
        '619' => 'PREMIUM NET (619)',
        '620' => 'KIFU (620)',
        '621' => 'UNITED TELECOM (621)',
        '622' => 'COPYDATA (622)',
        '623' => 'MOSONTELECOM (623)',
        '625' => 'CALLIOTEL (625)',
        '626' => 'VMTELE (626)',
        '627' => 'INVINETWORK (627)',
        '701' => 'FCS (701)',
        '707' => 'SKAWA (707)',
        '708' => 'PENDOLA INVEST (708)',
        '709' => 'VNM (709)',
        '711' => 'GERGI (711)',
        '712' => 'DUAL-PLUS (712)',
        '716' => 'BORSODWEB (716)',
        '717' => 'R-VOICE (717)',
        '721' => 'RENDSZERINFORMATIKA (721)',
        '724' => 'NISZ (724)',
        '726' => 'LAST-MILE (726)',
        '730' => 'TECHNO-TEL (730)',
        '731' => 'VIRCOMM (731)',
        '732' => 'CG-SYSTEMS (732)',
        '735' => 'HIR-SAT (735)',
        '737' => 'GIGANET (737)',
        '740' => 'HUNINF (740)',
        '741' => 'PRINTER-FAIR (741)',
        '742' => 'DELTAKON (742)',
        '743' => 'CBN TELEKOM (743)',
        '747' => 'FOLDESI (747)',
        '752' => 'NET-TV (752)',
        '753' => 'NETFONE TELECOM (753)',
        '765' => 'KABELSZATNET (765)',
        '766' => 'MVM NET (766)',
        '767' => 'INPHONE (767)',
        '768' => 'KALASZNET (768)',
        '769' => 'VIDEKHALO (769)',
        '770' => 'I3 (770)',
        '771' => 'TEVETV (771)',
        '774' => 'COGITNET (774)',
        '776' => 'WAVECOM (776)',
        '778' => 'BANKTEL (778)',
        '779' => 'CALGO (779)',
        '781' => 'EXPERTCOM (781)',
        '782' => 'ADERTIS (782)',
        '783' => 'MCN (783)',
        '784' => 'HELLOVOIP (784)',
        '786' => 'COST CONSULTING (786)',
        '789' => 'VCC LIVE (789)',
        '790' => 'UPC DIRECT (790)',
        '791' => '42NETMEDIA (791)',
        '792' => 'EPHONE SCHWEIZ (792)',
        '794' => 'PIVO (794)',
        '795' => 'NET-CONNECT (795)',
        '796' => 'EPAX (796)',
        '798' => 'BEROTEL (798)',
        '805' => 'PICKUP (805)',
        '807' => 'VIDANET (807)',
        '810' => 'PAZMANY (810)',
        '814' => 'EUROCABLE (814)',
        '816' => 'MICROSYSTEM (816)',
        '817' => 'INTELLIHOME (817)',
        '820' => 'AMTEL (820)',
        '822' => 'MEDIA EXCHANGE (822)',
        '823' => 'VOXBONE (823)',
        '826' => 'IP-TELEKOM (826)',
        '830' => 'SAGHY-SAT (830)',
        '833' => 'KAPOS (833)',
        '834' => 'KABLEX (834)',
        '835' => 'BTM (835)',
        '838' => 'ZNET (838)',
        '839' => 'CORVUS (839)',
        '841' => 'ACE (841)',
        '842' => 'BALMAZ (842)',
        '844' => 'COMTEST (844)',
        '845' => 'INVITEL TECHNOCOM (845)',
        '846' => 'FONIO (846)',
        '850' => 'ANTENNA HUNGARIA (850)',
        '855' => 'NET-PORTAL (855)',
        '857' => 'CELLDOMOLK (857)',
        '861' => 'MICRO-WAVE (861)',
        '862' => 'SOLARTEAM (862)',
        '863' => 'OPTICON (863)',
        '867' => 'DRAVANET (867)',
        '869' => 'KABELSAT (869)',
        '870' => 'ES INNOTEL (870)',
        '879' => 'SZAMOSNET (879)',
        '880' => 'TLT (880)',
        '883' => 'NOVI-COM (883)',
        '886' => 'MATI (886)',
        '891' => 'ELEKTRONET (891)',
        '894' => 'SATELIT (894)',
        '896' => 'TOLDINET (896)',
        '899' => 'NARACOM (899)',
        '902' => '3C (902)',
        '903' => 'BT (903)',
        '904' => 'MACROGATE (904)',
        '905' => '4VOICE (905)',
        '916' => 'TELEKOM FIX (916)',
        '917' => 'VODAUPC FIX (917)',
        '918' => 'INVITECH (918)',
        '923' => 'TARR (923)',
        '927' => 'OROS-COM (927)',
        '932' => 'INVITEL (932)',
        '933' => 'PENDOLA TELECOM (933)',
        '934' => 'TELEKOM FIX (934)',
        '935' => 'BIATORBAGYI KTV (935)',
        '936' => 'INTERNET-X (936)',
        '940' => 'VODAUPC FIX (940)',
        '941' => 'ON LINE SYSTEM (941)',
        '943' => 'ISISCOM (943)',
        '948' => 'DIGI (948)',
        '953' => 'PR-TELECOM (953)',
        '956' => 'TELEKOM FIX (956)',
        '958' => 'N-SYSTEM (958)',
        '961' => 'OPENNETWORKS (961)',
        '966' => 'COMUNIQUE (966)',
        '967' => 'MIKROHALO (967)',
        '976' => 'ARRABONET (976)',
        '979' => 'ZALASZAM (979)',
        '981' => 'XYTON (981)',
        '983' => 'VCC LIVE (983)',
        '984' => 'NORDTELEKOM (984)',
        '986' => 'TRIOTEL (986)',
        '989' => 'PARISAT (989)',
        '993' => 'RLAN (993)',
        '603' => 'TARR MOBIL (603)',
        '604' => 'DIGI MOBIL (604)',
        '617' => 'NETFONE TELECOM MOBIL (617)',
        '760' => 'VODAUPC MOB (760)',
        '777' => 'NETFONE TELECOM MOBIL (777)',
        '919' => 'TELENOR (919)',
        '926' => 'VODAFONE (926)',
        '928' => 'TELEKOM MOBIL (928)',
        '900' => 'NMHH-V (900)',
        '901' => 'NMHH-M (901)',
        '749' => '-',
        '987' => '-',
        '601' => 'RWHC (601)',
        '610' => 'I-TELECOM (610)',
        '702' => 'ACN (702)',
        '703' => 'ALFA-DH (703)',
        '704' => 'HETENYEGYHAZA (704)',
        '705' => 'USCALL (705)',
        '706' => 'CORANET (706)',
        '710' => 'MICROSEMIC (710)',
        '713' => 'SZABO ELEKTRONIKA (713)',
        '714' => 'ATC (714)',
        '715' => '1212TELEKOM (715)',
        '718' => 'AKTIV-I (718)',
        '719' => 'VIP ONE (719)',
        '720' => 'WEBLAN (720)',
        '722' => 'BSYSTEMS (722)',
        '723' => 'VIP TELEKOM (723)',
        '725' => 'TESCO MOBILE (725)',
        '727' => 'DIRECT VISION (727)',
        '728' => 'SUPRA (728)',
        '729' => 'HUCOM (729)',
        '733' => '3 LAN (733)',
        '734' => 'TEL2U (734)',
        '736' => 'H1 TELEKOM (736)',
        '738' => 'HELLO HD (738)',
        '739' => 'ZIONET (739)',
        '744' => 'BARONETCOMP (744)',
        '745' => 'ZUBOR (745)',
        '746' => 'IKRON (746)',
        '748' => 'FALU-TV (748)',
        '750' => 'RUBICOM DIGITAL (750)',
        '751' => 'CITI TELEKOM (751)',
        '754' => 'GIGABIT (754)',
        '755' => 'DUALCOMP (755)',
        '756' => 'ISAVE (756)',
        '757' => 'CLOUDPRIME (757)',
        '758' => 'SZABADHAJDU (758)',
        '759' => 'CALLTIVATION (759)',
        '761' => 'DELTAMIKRO (761)',
        '762' => 'KOLESZ (762)',
        '763' => 'PRIM TELEKOM (763)',
        '764' => 'EVISION (764)',
        '772' => 'M70 (772)',
        '773' => 'REKO (773)',
        '775' => 'CITITELEKOM ZRT (775)',
        '780' => 'EXTRANET (780)',
        '785' => 'CONPHONE (785)',
        '787' => 'GS-NET (787)',
        '788' => 'MOND21 (788)',
        '793' => 'NEMETH ROBERT (793)',
        '797' => 'RAYCOM-GTE (797)',
        '799' => 'FIX TELEKOM (799)',
        '801' => 'TIGER (801)',
        '802' => 'INVITEL (802)',
        '803' => 'VOICE-COM (803)',
        '804' => 'RUBICOM (804)',
        '806' => 'DT (806)',
        '808' => 'BACSKABEL (808)',
        '809' => 'ZELKA (809)',
        '811' => 'KFL KFT (811)',
        '812' => 'AGNATUS (812)',
        '813' => 'VAR-TECH (813)',
        '815' => 'GYORNET (815)',
        '818' => 'SZABOLCS (818)',
        '819' => 'HFC (819)',
        '821' => 'ARCADOM (821)',
        '824' => 'BABYLONPHONE (824)',
        '825' => 'BICOMIX (825)',
        '827' => 'MIRSA (827)',
        '828' => 'CSB-IMMO (828)',
        '829' => 'CENTER (829)',
        '831' => 'ORITEL (831)',
        '832' => 'TELELINE (832)',
        '836' => 'PANNON PIPICS (836)',
        '837' => 'DIELNET (837)',
        '840' => 'BERENYI (840)',
        '843' => 'OKSZI (843)',
        '847' => 'ENTERNET (847)',
        '848' => 'PRIVATE TEL (848)',
        '849' => 'KALOCSAKOM (849)',
        '851' => 'NETGEN',
        '852' => 'VOIP SYSTEM (852)',
        '853' => 'DD-CAD (853)',
        '854' => 'CREACOM (854)',
        '856' => 'HIPHONE (856)',
        '858' => 'MICRO-TELECOM (858)',
        '859' => 'SYSCORP (859)',
        '860' => 'KISKOROS (860)',
        '864' => 'INTELEKOM (864)',
        '865' => 'AGORA (865)',
        '866' => 'INTV (866)',
        '868' => 'MILENIA (868)',
        '871' => 'TENETTEL (871)',
        '872' => 'NETSURF (872)',
        '873' => 'LESKO-NAGY (873)',
        '874' => 'SONITAR (874)',
        '875' => 'LCCK (875)',
        '876' => 'NETWORK TELEKOM (876)',
        '877' => 'ALLCOM (877)',
        '878' => '1A HOSTING (878)',
        '881' => 'VOIP NETCOM  (881)',
        '882' => 'EQNET (882)',
        '884' => 'INT-AIRNET (884)',
        '885' => 'SYMLINK (885)',
        '887' => 'VIPTEL (887)',
        '888' => 'TIGER SYSTEMS (888)',
        '889' => 'QUAESTEL (889)',
        '890' => 'EPHONE ZRT',
        '892' => 'VOIPSHOP (892)',
        '893' => 'ISAFE (893)',
        '895' => 'VERIZON (895)',
        '897' => 'KFL-NETWORKING (897)',
        '898' => 'INTEREURO (898)',
        '906' => 'TELEKOM FIX (906)',
        '907' => 'VOIP TELEKOM (907)',
        '908' => 'OPTANET (908)',
        '909' => 'GTS_I (909)',
        '910' => 'NAVIGATOR (910)',
        '911' => 'GTS (911)',
        '912' => 'INVITEL (912)',
        '913' => 'IOCOM (913)',
        '915' => 'BUSINESS TELECOM (915)',
        '920' => 'PANTEL Holding (920)',
        '921' => 'DKTV (921)',
        '922' => 'INVITEL (922)',
        '929' => 'NETFONE (929)',
        '930' => 'WNET (930)',
        '931' => 'RADIOLAN (931)',
        '937' => 'TVNETWORK (937)',
        '938' => 'TELE2 (938)',
        '939' => 'HUNGAROCOM (939)',
        '942' => 'FARAGO SANDOR (942)',
        '944' => 'IDC (944)',
        '945' => 'ATLAS TELECOM (945)',
        '946' => 'EXTERNET (946)',
        '947' => 'HUNNET (947)',
        '949' => 'EPHONE KFT (949)',
        '950' => 'MYPHONE (950)',
        '952' => 'KAPULAN (952)',
        '954' => 'CORPORATE UNITED (954)',
        '955' => 'TVNET (955)',
        '957' => 'INTELECOM (957)',
        '959' => 'FONE (959)',
        '960' => 'DUNAKANYAR (960)',
        '963' => 'INTERNET4U (963)',
        '965' => 'ACTEL (965)',
        '969' => 'FONETCOM (969)',
        '970' => 'INVITEL (970)',
        '971' => 'JUROP TELEKOM (971)',
        '973' => 'CBN (973)',
        '977' => 'VIVAFONE (977)',
        '978' => 'DESIGNER TEAM (978)',
        '980' => 'TOMICTEL (980)',
        '985' => 'INECTEL (985)',
        '988' => 'ALL INFO EUROPA (988)',
        '992' => 'EURO21 (992)',
    ];
    */

    /**/
    private $_operators = [
        841 => 'ACE TELECOM Telekommunikációs és Informatikai Szolgáltató Kft. ',
        702 => 'ACN Communications Hungary Kft. ',
        965 => 'Actel Távközlési Zrt. ',
        782 => 'ADERTIS Informatikai Fejlesztő és Szolgáltató Kft. ',
        812 => 'Agnátus-Pont 2004 Távközlési Szolgáltató Kereskedelmi és Ipari Kft. ',
        718 => 'Aktív-I Szolgáltató Kft. ',
        703 => 'Alfa-DH Kereskedelmi és Szolgáltató Kft. ',
        988 => 'All Info Európa Informatikai, Távközlési és Tanácsadó Kft. ',
        877 => 'ALLCOM Hungary Távközlési és Szolgáltató Kft. ',
        820 => 'AMTEL Hang és Internet Kommunikáció Magyarország Kft. ',
        850 => 'ANTENNA HUNGÁRIA Magyar Műsorszóró és Rádióhírközlési Zrt. ',
        821 => 'Arcadom Gyengeáramú és Biztonságtechnikai Kereskedelmi és Szolgáltató Kft. ',
        976 => 'ArraboNet Kereskedelmi és Szolgáltató Kft. ',
        714 => 'A.T.C. Avant Telecom Consulting AG ',
        945 => 'Atlas Telecom Távközlési Szolgáltató Kft. ',
        824 => 'Babylonphone Információ-technológiai és szolgáltató Kft. ',
        808 => 'BÁCSKÁBEL Informatikai Fejlesztő és Szolgáltató Kft. ',
        842 => 'Balmaz InterCOM Távközlési és Szolgáltató Kft. ',
        778 => 'Banktel Kommunikációs Zrt. ',
        744 => 'Baronetcomp Kft. ',
        840 => 'Berényi Kereskedelmi és Szolgáltató Kft. ',
        798 => 'Berotel Networks Kft. ',
        935 => 'Biatorbágyi Kábeltévé Szolgáltató és Kereskedelmi Kft. ',
        825 => 'BICOMIX Kereskedelmi és Szolgáltató Kft. ',
        716 => 'BORSODWEB Internet Szolgáltató Kft. ',
        722 => 'Bsystems Telekom Kft. ',
        903 => 'BT Limited Magyarországi Fióktelepe ',
        835 => 'BTM 2003 Kereskedelmi és Szolgáltató Kft. ',
        915 => 'Business Telecom Távközlési Nyrt. ',
        779 => 'Calgo Kft. ',
        759 => 'Calltivation Ltd. ',
        743 => 'CBN Telekom Kft. ',
        857 => 'Celldömölki Kábeltelevízió Műsorelosztó Kft. ',
        829 => 'Center Telecom Kft. ',
        732 => 'CG-SYSTEMS Informatikai, Kereskedelmi és Szolgáltató Kft. ',
        751 => 'Citi Telekom Limited ',
        775 => 'Citi Telekom Zrt. ',
        757 => 'CloudPrime Szolgáltató és Tanácsadó Kft. ',
        774 => 'Cogitnet Informatikai Kft. ',
        844 => 'Comtest Technikai és Ügyvitelszervezési Kft. ',
        785 => 'ConPhone Audio Conferening Kft. ',
        706 => 'Cor@Net Távközlési Zrt. ',
        954 => 'Corporate United Szolgáltató Kft. ',
        973 => 'CORRECT BUSINESS NETWORK Távközlési Szolgáltató Kft. ',
        839 => 'Corvus Telecom Informatikai és Távközlési Kft. ',
        786 => 'Cost Consulting Szolgáltató Kft. ',
        854 => 'CreaCom Média Információszolgáltató és Telekommunikációs Kft. ',
        828 => 'CSB-IMMO Ingatlanfejlesztő és Üzemeltető Kft. ',
        853 => 'DD-Cad Tervező és Szolgáltató Kft. ',
        742 => 'DELTAKON Kereskedelmi és Szolgáltató Kft. ',
        761 => 'Deltamikro Kereskedelmi és Szolgáltató Kft. ',
        978 => 'Designer Team Mérnökiroda és Szolgáltató Kft. ',
        837 => 'Dielnet Távközlési Kereskedelmi és Szolgáltató Kft . ',
        948 => 'DIGI Távközlési és Szolgáltató Kft. ',
        604 => 'DIGI Távközlési és Szolgáltató Kft. ',
        727 => 'Direct Vision Kft. ',
        921 => 'DKTV Távközlési Kereskedelmi és Szolgáltató Kft. ',
        867 => 'DRÁVANET Internet Szolgáltató Zrt. ',
        806 => 'DT Tanácsadó Kft. ',
        755 => 'Dualcomp Trade Kft. ',
        712 => 'DUAL-PLUS Szolgáltató és Kereskedelmi Kft. ',
        960 => 'DUNAKANYAR-HOLDING Pénzügyi Tanácsadó és Szolgáltató Kft. ',
        891 => 'ELEKTRONET Elektronikai és Telekommunikációs ZRt. ',
        847 => 'EnterNet 2001 Számítástechnikai Szolgáltató és Kereskedelmi Kft. ',
        796 => 'Epax Korlátolt Felelősségű Társaság ',
        949 => 'Ephone Magyarország Távközlési, Kivitelező és Szolgáltató Kft. ',
        792 => 'Ephone Schweiz GmbH. ',
        890 => 'Ephone Telekommunikációs Zrt. ',
        882 => 'EQNet Infokommunikációs Zrt. ',
        870 => 'ES Innotel Kft. ',
        814 => 'EuroCable Magyarország Kábeltelevíziós, Kereskedelmi és Szolgáltató Kft. ',
        764 => 'eVision Kereskedelmi és Szolgáltató Kft. ',
        781 => 'ExpertCom Kft. ',
        946 => 'Externet Telekommunikációs és Internet Szolgáltató Zrt. "csődeljárás alatt" ',
        780 => 'Extranet Internet Kft. ',
        748 => 'Falu-TV Szolgáltató Kft. ',
        942 => 'Faragó Sándor ',
        701 => 'FCS Group Kereskedelmi, Szolgáltató és Tanácsadó Kft. ',
        799 => 'FIX TELEKOM Kft. ',
        959 => 'Fone Távközlési, Kereskedelmi és Szolgáltató Kft. ',
        969 => 'Fonetcom Kábel-TV, Telefon és Internet Szolgáltató Kft. ',
        846 => 'FONIO-VOIP Informatikai, Kereskedelmi és Szolgáltató Kft. ',
        747 => 'Földesi és Társa 2002 Kereskedelmi és Szolgáltató Kft. ',
        612 => 'Gelka Hirtech Kereskedelmi és Szolgáltató Kft. ',
        711 => 'Gergi Háló Szolgáltató és Kereskedelmi Kft. ',
        754 => 'GigaBit Kereskedelmi és Informatikai Szolgáltató Kft. ',
        737 => 'Giganet Internet Szolgáltató Kft. ',
        602 => 'Greencom Hungary Kft. ',
        787 => 'GS-Net Kft. ',
        911 => 'GTS Hungary Távközlési Kft. ',
        909 => 'GTS Hungary Távközlési Kft. ',
        815 => 'GYŐR.NET Internetszolgáltató Kft. ',
        865 => 'HB Agora Kereskedelmi és Szolgáltató Kft. ',
        609 => 'HBCom Kábel Nonprofit Kft. ',
        738 => 'HELLO HD Kereskedelmi és Szolgáltató Kft. ',
        784 => 'HelloVoip Kft. ',
        704 => 'Hetényegyháza Kábeltelevízió Kereskedelmi és Szolgáltató KFt. ',
        819 => 'HFC Network Kivitelező és Szolgáltató Kft. ',
        735 => 'HIR-SAT 2000 Szolgáltató és Kereskedelmi Kft. ',
        729 => 'HuCom Telecom Kft. ',
        740 => 'Hungária Informatikai Kft. ',
        939 => 'HUNGAROCOM ',
        856 => 'Hungary Invest Kereskedelmi és Szolgáltató Kft. ',
        947 => 'HunNet Hungarian Networks Számítástechnikai, Oktatási és Kereskedelmi Kft. ',
        605 => 'H1 Komm Távközlési és Kereskedelmi Kft. ',
        736 => 'H1 Telekom Távközlési és Kereskedelmi Kft. ',
        944 => 'IDC ',
        746 => 'IKRON Fejlesztő és Szolgáltató Kft. ',
        985 => 'INECTEL ',
        767 => 'Inphone Adatfeldolgozó és Információs Szolgáltató Kft. ',
        884 => 'Int-air.net Számítástechnikai Szolgáltató Kft. ',
        957 => 'INTELECOM ',
        864 => 'INTELEKOM SYSTEMS Kft. ',
        817 => 'Intellihome Távközlési Szolgáltató Kft. ',
        898 => 'InterEuro Computer Kereskedelmi és Szolgáltató Kft. ',
        936 => 'Internet-X Magyarország Internet Szolgáltató és Kereskedelmi Kft. ',
        963 => 'INTERNET4U ',
        866 => 'InTV Kereskedelmi és Szolgáltató Kft. ',
        918 => 'Invitech Megoldások Zrt. ',
        932 => 'Invitel Távközlési Zrt. ',
        970 => 'Invitel Távközlési Zrt. ',
        922 => 'Invitel Távközlési Zrt. ',
        802 => 'Invitel Távközlési Zrt. ',
        912 => 'Invitel Távközlési Zrt. ',
        845 => 'Invitel Technocom Távközlési Kft. ',
        913 => 'IOCom Kereskedelmi és Szolgáltató Kft. ',
        826 => 'IP-Telekom Informatikai és Távközlési Kft. ',
        893 => 'iSAFE Informatikai Zrt. ',
        756 => 'iSave Informatika Kft. ',
        943 => 'Isis-Com Szolgáltató Kereskedelmi Kft. ',
        610 => 'i-Telecom Hungary Kft. ',
        770 => 'i3 Rendszerház Informatikai Kereskedelmi és Szolgáltató Kft. ',
        887 => 'Juhász Ervin ',
        971 => 'JUROP TELEKOM Telekommunikációs Kft. ',
        869 => '"KÁBELSAT-2000" Kábeltelevízió Építő- és Szolgáltató Kft. ',
        765 => 'KábelszatNet-2002 Műsorelosztó és Kereskedelmi Kft. ',
        834 => 'Káblex Kereskedelmi és Szolgáltató Kft. ',
        966 => 'Kalásznet Kábel TV Kft. ',
        768 => 'Kalásznet Kábel TV Kft. ',
        849 => 'KalocsaKOM Kommunikációs és Szolgáltató Kft. ',
        833 => 'Kapos-NET Szolgáltató és Kereskedelmi Kft. ',
        952 => 'Kapulan Kereskedelmi és Távközlési Kft. ',
        811 => 'KFL Informatikai és Szolgáltató Kft. ',
        992 => 'KFL Kereskedelmi és Informatikai Bt. ',
        897 => 'KFL-NETWORKING Telekommunikációs és Informatikai Kft. ',
        860 => 'KISKŐRÖSI KÁBEL-TELEVÍZIÓ Kft. ',
        762 => 'Kölcsön-Eszköz Vagyon- és Eszközkezelő Kft. ',
        726 => 'Last-Mile Telekommunikációs Kereskedelmi és Szolgáltató Kft. ',
        875 => 'LCCK Számítástechnikai és Informatikai Bt. ',
        873 => 'Leskó és Nagy Kft. ',
        904 => 'MACROgate IPsystems Magyarország Kft. ',
        934 => 'Magyar Telekom Távközlési Nyrt. ',
        906 => 'Magyar Telekom Távközlési Nyrt. ',
        956 => 'Magyar Telekom Távközlési Nyrt. ',
        928 => 'Magyar Telekom Távközlési Nyrt. ',
        916 => 'Magyar Telekom Távközlési Nyrt. ',
        886 => 'Magyar Telekommunikációs és Informatikai Kft. ',
        783 => 'MCN telecom Telekommunikációs Szolgáltató Kft. ',
        611 => 'MCNtelecom GmbH ',
        822 => 'Media Exchange Kereskedelmi és Szolgáltató Kft. ',
        710 => 'Microsemic Kft. ',
        816 => 'Microsystem Kecskemét Kereskedelmi és Szolgáltató Kft. ',
        858 => 'Micro-Telecom Telekommunikációs Kereskedelmi és Szolgáltató Kft. ',
        861 => 'MICRO-WAVE Kereskedelmi és Szolgáltató Kft. ',
        967 => 'Mikroháló Távközlési, Szolgáltató Kft. ',
        868 => 'Milenia-Systems Kereskedelmi és Szolgáltató Kft. ',
        827 => 'MIRSA EUROMOBILE Kereskedelmi és Szolgáltató Kft. ',
        788 => 'Mond21 Telekommunikációs Zrt. ',
        766 => 'MVM NET Távközlési Szolgáltató Zrt. ',
        950 => 'MyPhone Kereskedelmi és Szolgáltató Kft. ',
        772 => 'M70 Group Korlátolt Felelősségű Társaság ',
        899 => 'NARACOM Informatikai Kft. ',
        910 => 'Navigator Informatika Üzleti Szolgáltató és Kereskedelmi Zrt. ',
        793 => 'Németh Róbert ',
        900 => 'Nemzeti Média- és Hírközlési Hatóság ',
        901 => 'Nemzeti Média- és Hírközlési Hatóság ',
        795 => 'Net-Connect Communications SRL ',
        929 => 'Netfone Távközlési Szolgáltató Kft. ',
        753 => 'Netfone Telecom Távközlési és Szolgáltató Kft. ',
        777 => 'Netfone Telecom Távközlési és Szolgáltató Kft. ',
        851 => 'NetGen Infokommunikációs Kft. ',
        855 => 'Net-Portal Távközlési, Kereskedelmi és Szolgáltató Kft. ',
        872 => 'Netsurf Távközlési Szolgáltató Kft. ',
        752 => 'Net-Tv Zrt. ',
        876 => 'Network Telekom Kereskedelmi és Szolgáltató Kft. ',
        614 => 'nfon GmbH ',
        724 => 'NISZ Nemzeti Infokommunikációs Szolgáltató Zrt. ',
        984 => 'Nordtelekom Távközlési Szolgáltató Nyrt. ',
        883 => 'Novi-Com Kereskedelmi és Szolgáltató Kft. ',
        958 => 'N-System Távközlési Szolgáltató Kft. ',
        843 => '"OKSZI" Oktatói, Kereskedelmi és Szolgáltató Kft. ',
        941 => 'On Line System Informatikai és Tanácsadó Kft. ',
        961 => 'Opennetworks Kereskedelmi és Szolgáltató Kft. ',
        908 => 'Optanet Kft. ',
        863 => 'Opticon Telekommunikációs Hálózati Szolgáltató Kft. ',
        927 => 'Oros-Com Informatikai Szolgáltató Kft. ',
        831 => 'Oroszlányi Televízió Kft. ',
        836 => 'Pannon Pipics Szolgáltató és Kereskedelmi Kft. ',
        920 => 'PANTEL Holding ',
        989 => 'PARISAT Távközlési és Szolgáltató Kft. ',
        810 => 'Pázmány Kábel Szolgáltató Kft. ',
        708 => 'Pendola Invest Távközlési és Szolgáltató Kft. ',
        933 => 'Pendola TeleCom Szolgáltató Kft. ',
        805 => 'PICKUP Elektronikai Kereskedelmi és Szolgáltató Kft. ',
        794 => 'PIVo Telecom Kft. ',
        763 => 'PRIM TELEKOM Kft. ',
        741 => 'Printer-fair Számítástechnikai, Kereskedelmi és Szolgáltató Kft. ',
        848 => 'PRIVATE TEL Kereskedelmi és Szolgáltató Kft. ',
        953 => 'PR-TELECOM Távközlési, Kereskedelmi és Szolgáltató Zrt. ',
        889 => 'QuaesTel Telekommunikációs Kft. ',
        931 => 'RadioLAN Távközlési és Szolgáltató Kft. ',
        797 => 'RAYCOM-GTE Kereskedelmi és Szolgáltató Korlátolt Felelősség Társaság ',
        607 => 'Raystorm Kft ',
        608 => 'Rebell Telecommunication Zrt. ',
        773 => 'ReKo Systems Informatikai, Kereskedelmi és Szolgáltató Korlátolt Felelősségű Társaság ',
        721 => 'Rendszerinformatika Kereskedelmi és Szolgáltató Zrt. ',
        993 => 'RLAN Internet Távközlési Szolgáltató Kft. ',
        601 => 'RowanHill Communications Kft. ',
        750 => 'RubiCom Digital Kft. ',
        804 => 'RubiCom Távközlési ZRt. ',
        717 => 'R-Voice Hungary Telekommunikációs és Informatikai Kft. ',
        830 => 'Sághy-Sat Szolgáltató és Kereskedelmi Kft. ',
        894 => 'SATELIT Híradástechnikai Kft. ',
        707 => 'SKAWA Innovation Kutatás-Fejlesztési Kft. ',
        862 => 'SolarTeam Energia Szolgáltató és Kereskedelmi Kft. ',
        874 => 'Sonitar Kereskedelmi és Szolgáltató Kft. ',
        728 => 'SUPRA Kábeltelevíziós Kereskedelmi és Szolgáltató Kft. ',
        885 => 'Symlink Informatikai Szolgáltató és Tanácsadó Kft. ',
        859 => 'SysCorp Számítástechnikai és Telekommunikációs Kft. ',
        758 => 'Szabadhajdú Közművelődési Média és Rendezvényszervező Nonprofit Kft. ',
        713 => 'Szabó Elektronika Kft. ',
        818 => 'Szabolcs Kábeltelevízió Szolgáltató és Kereskedelmi Kft. ',
        879 => 'Szamosnet Informatikai és Telekommunikációs Szolgáltató Kft. ',
        923 => 'Tarr Építő, Szolgáltató és Kereskedelmi Kft. ',
        603 => 'Tarr Építő, Szolgáltató és Kereskedelmi Kft. ',
        730 => 'Techno-Tel Távközlési és Informatikai Kivitelező és Szolgáltató Kft. ',
        832 => 'Teleline 95. Kereskedelmi és Szolgáltató KFt. ',
        919 => 'Telenor Magyarország Zrt. ',
        938 => 'TELE2 ',
        734 => 'Tel2U Távközlési és Szolgáltató Kft. ',
        871 => 'TENETTEL Távközlési Szolgáltató Kft. ',
        725 => 'Tesco MBL Távközlési Zrt. ',
        771 => 'TEVE TÉVÉ Kereskedelmi és Távközlési Szolgáltató Kft. ',
        888 => 'Tiger Systems Kereskedelmi és Szolgáltató Kft. ',
        801 => 'Tiger Telekom Kereskedelmi és Szolgáltató Kft. ',
        613 => 'Tiszafüredi Kábeltévé Szövetkezet ',
        880 => '"TLT Telecom" Távközlési és Informatikai Kft. ',
        896 => 'Toldinet Internet Szolgáltató Kft. ',
        980 => 'TOMICTEL ',
        986 => 'Triotel Távközlési Kft. ',
        955 => 'TVNET ',
        937 => 'TvNetWork Telekommunikációs Szolgáltató NyRt. ',
        606 => 'UHU Systems Számítástechnikai Kft. ',
        790 => 'UPC DTH S.á.r.l. ',
        917 => 'UPC Magyarország Telekommunikációs Kft. ',
        940 => 'UPC Magyarország Telekommunikációs Kft. ',
        760 => 'UPC Magyarország Telekommunikációs Kft. ',
        705 => 'USCALL Telekommunikációs Zártkörüen Működő Részvénytársaság ',
        813 => 'Vár-Tech Szolgáltató Kft. ',
        789 => 'VCC Live Hungary Kft. ',
        983 => 'VCC Live Hungary Kft. ',
        895 => 'Verizon Magyarország Távközlési Kft. ',
        807 => 'ViDaNet Kábeltelevíziós Szolgáltató Zrt. ',
        769 => 'Vidékháló Telekommunikációs Kft. ',
        723 => 'VIP Telekom Hungary Kft. ',
        719 => 'V.I.P. Ügyfelek Tanácsadó és Szolgáltató Kft. ',
        731 => 'Virtual Communications Kft. ',
        977 => 'VIVAFONE ',
        709 => 'VNM Zrt. ',
        926 => 'Vodafone Magyarország Mobil Távközlési Zrt. ',
        803 => 'Voice-Com Szolgáltató és Kereskedelmi Kft. ',
        881 => 'VoIP NetCom Telekommunikációs Távközlési Szolgáltató Kft. ',
        852 => 'VoIP System Kft. ',
        907 => 'Voip Telekom Hungary Kereskedelmi és Szolgáltató Kft. ',
        892 => 'VoIPShop Távközlési Szolgáltató Kft. ',
        823 => 'Voxbone S.A. ',
        776 => 'Wavecom Informatikai Kereskedelmi és Szolgáltató Kft. ',
        720 => 'WebLan Magyarország Kft. ',
        930 => 'WNET Internet Távközlési Szolgáltató Kft. ',
        981 => 'Xyton Kft. ',
        809 => 'Zalaegerszegi Elektromos Karbantartó és Kereskedelmi Zrt. ',
        979 => 'Zalaszám Informatika Kft. ',
        739 => 'Zionet Informatikai, Ipari, Kereskedelmi és Szolgáltató Kft. ',
        838 => 'ZNET Telekom Zrt. ',
        745 => 'Zubor László ',
        878 => '1A Hosting Kft. ',
        715 => '1212 Telekom Gazdasági Szolgáltató Kft. ',
        902 => '3C Távközlési Kft. ',
        733 => '3LAN Kereskedelmi és Szolgáltató Kft. ',
        905 => '4VOICE Távközlési Kft. ',
        791 => '42NETMedia Szolgáltató Kft. ',

        615 => 'DIALOGA SERVICIOS INTERACTIVOS, S.A.',
        616 => 'Medveczky Cégcsoport Kft.',
        617 => 'Netfone Telecom Távközlési és Szolgáltató Kft.',
        618 => 'Kis Fal Kft.',
        621 => 'United Telecom Zrt.',
        622 => 'Copy-Data Kereskedelmi és Szolgáltató Kft.',
    ];
/**/
    /**
     * @inheritdoc
     * @throws \yii\base\InvalidParamException
     * @throws \yii\web\NotFoundHttpException
     * @throws \yii\db\Exception
     * @throws \LogicException
     */
    protected function readData()
    {
        $fileUrl = \Yii::getAlias('@runtime/' . $this->fileName);
        $fp = fopen($fileUrl, 'r');
        if (!$fp) {
            throw new NotFoundHttpException('Ошибка чтения файла ' . $fileUrl);
        }

        $insertValues = [];
        while (($row = fgets($fp)) !== false) {

//            $row = trim(str_replace(['<list_item>', '</list_item>'], '', $row));
            $row = trim($row);

            if (strpos($row, '</list>') !== false) {
                $row = str_replace('</list>', '', $row);
            }

            if (!$row || $row == '<list>' || $row == '</list>') {
                continue;
            }

            try {
                $xml = simplexml_load_string($row);
            } catch (\Exception $e) {
                echo PHP_EOL . 'error: ' . $e->getMessage();
                echo PHP_EOL . $row;
                continue;
            }

            if (!$xml) {
                echo 'Неправильные данные: ' . $row . PHP_EOL;
                continue;
            }

            $number = (string)$xml->phone_number;
            if (!$number || !is_numeric($number)) {
                throw new \LogicException('Неправильный номер: ' . $row);
            }

            $number = Country::HUNGARY_PREFIX . $number;

            $operatorName = (string)$xml->actual_provider;
            if ($operatorName && !isset($this->_operators[$operatorName])) {
                echo PHP_EOL . 'operator not found: ' . $operatorName;
            }

            if ($operatorName && isset($this->_operators[$operatorName]) && $this->_operators[$operatorName]) {
                $operatorName = $this->_operators[$operatorName];
            }

            $insertValues[] = [$number, $operatorName];

            if (count($insertValues) >= self::CHUNK_SIZE) {
                $this->insertValues(Country::HUNGARY, $insertValues);
            }
        }

        fclose($fp);

        if ($insertValues) {
            $this->insertValues(Country::HUNGARY, $insertValues);
        }
    }
}
