// Generated by CoffeeScript 1.10.0
(function() {
  var AccounttariffEdit,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  AccounttariffEdit = (function() {
    AccounttariffEdit.prototype.country = null;

    AccounttariffEdit.prototype.numberType = null;

    AccounttariffEdit.prototype.city = null;

    AccounttariffEdit.prototype.didGroup = null;

    AccounttariffEdit.prototype.numbersList = null;

    AccounttariffEdit.prototype.numbersListSelectAll = null;

    AccounttariffEdit.prototype.numbersListSelectAllCheckbox = null;

    AccounttariffEdit.prototype.numbersListFilter = null;

    AccounttariffEdit.prototype.numbersListClass = null;

    AccounttariffEdit.prototype.numbersListOrderByField = null;

    AccounttariffEdit.prototype.numbersListOrderByType = null;

    AccounttariffEdit.prototype.numbersListMask = null;

    AccounttariffEdit.prototype.numbersListLimit = null;

    AccounttariffEdit.prototype.tariffDiv = null;

    AccounttariffEdit.prototype.tariffPeriod = null;

    AccounttariffEdit.prototype.packageTariffPeriod = null;

    AccounttariffEdit.prototype.voipServiceTypeIdVal = null;

    AccounttariffEdit.prototype.voipPackageServiceTypeIdVal = null;

    AccounttariffEdit.prototype.currencyVal = null;

    AccounttariffEdit.prototype.form = null;

    AccounttariffEdit.prototype.errorClassName = 'alert-danger';

    AccounttariffEdit.prototype.successClassName = 'alert-success';

    function AccounttariffEdit() {
      this.onFormSubmit = bind(this.onFormSubmit, this);
      this.onTariffPeriodChange = bind(this.onTariffPeriodChange, this);
      this.showTariffDiv = bind(this.showTariffDiv, this);
      this.selectAllNumbers = bind(this.selectAllNumbers, this);
      this.showNumbersList = bind(this.showNumbersList, this);
      this.onCityChange = bind(this.onCityChange, this);
      this.onNumberTypeChange = bind(this.onNumberTypeChange, this);
      this.initCountry = bind(this.initCountry, this);
      this.onCountryChange = bind(this.onCountryChange, this);
      setTimeout((function(_this) {
        return function() {
          _this.country = $('#voipCountryId').on('change', _this.onCountryChange);
          _this.numberType = $('#voipNumberType').on('change', _this.onNumberTypeChange);
          _this.city = $('#voipRegions').on('change', _this.onCityChange);
          _this.didGroup = $('#voipDidGroup').on('change', _this.showNumbersList);
          _this.numbersList = $('#voipNumbersList').on('change', 'input', _this.showTariffDiv);
          _this.numbersListSelectAll = $('#voipNumbersListSelectAll');
          _this.numbersListSelectAllCheckbox = _this.numbersListSelectAll.find('input').on('change', _this.selectAllNumbers);
          _this.numbersListFilter = $('#voipNumbersListFilter');
          _this.tariffDiv = $('#voipTariffDiv');
          _this.numbersListClass = $('#voipNumbersListClass').on('change', _this.showNumbersList);
          _this.numbersListOrderByField = $('#voipNumbersListOrderByField').on('change', _this.showNumbersList);
          _this.numbersListOrderByType = $('#voipNumbersListOrderByType').on('change', _this.showNumbersList);
          _this.numbersListMask = $('#voipNumbersListMask').on('change', _this.showNumbersList);
          _this.numbersListLimit = $('#voipNumbersListLimit').on('change', _this.showNumbersList);
          _this.tariffPeriod = $('.accountTariffTariffPeriod').on('change', _this.onTariffPeriodChange);
          _this.packageTariffPeriod = $('#accountTariffPackageTariffPeriod');
          _this.voipServiceTypeIdVal = $('#voipServiceTypeId').val();
          _this.voipPackageServiceTypeIdVal = $('#voipPackageServiceTypeId').val();
          _this.currencyVal = $('#voipCurrency').val();
          _this.form = $('#addAccountTariffVoipForm').on('submit', _this.onFormSubmit);
          _this.initCountry(false);
          return _this.numberType.trigger('change');
        };
      })(this), 200);
    }

    AccounttariffEdit.prototype.onCountryChange = function() {
      return this.initCountry(true);
    };

    AccounttariffEdit.prototype.initCountry = function(isUpdateNumberTypesAndCities) {
      var countryVal;
      countryVal = this.country.val();
      if (countryVal) {
        if (isUpdateNumberTypesAndCities) {
          $.get('/uu/voip/get-number-types', {
            countryId: countryVal,
            isWithEmpty: true,
            format: 'options'
          }, (function(_this) {
            return function(html) {
              _this.numberType.html(html);
              _this.numberType.prop('disabled', false);
              return _this.numberType.val('').trigger('change');
            };
          })(this));
          $.get('/uu/voip/get-cities', {
            countryId: countryVal,
            isWithEmpty: true,
            format: 'options'
          }, (function(_this) {
            return function(html) {
              _this.city.html(html);
              return _this.city.val('').trigger('change');
            };
          })(this));
        }
        this.country.parent().parent().removeClass(this.errorClassName);
      } else {
        this.numberType.prop('disabled', true);
        this.numberType.val('').trigger('change');
        this.city.val('').trigger('change');
        this.country.parent().parent().addClass(this.errorClassName);
      }
      return this.city.prop('disabled', true);
    };

    AccounttariffEdit.prototype.onNumberTypeChange = function() {
      var numberTypeVal;
      numberTypeVal = this.numberType.val();
      if (this.numberType.prop('disabled') || numberTypeVal) {
        this.numberType.parent().parent().removeClass(this.errorClassName);
      } else {
        this.numberType.parent().parent().addClass(this.errorClassName);
      }
      if (numberTypeVal) {
        this.city.prop('disabled', false);
      } else {
        this.city.prop('disabled', true);
      }
      return this.city.trigger('change');
    };

    AccounttariffEdit.prototype.onCityChange = function() {
      var cityVal, numberTypeVal;
      cityVal = this.city.val();
      numberTypeVal = this.numberType.val();
      if (this.city.prop('disabled') || cityVal) {
        this.city.parent().parent().removeClass(this.errorClassName);
      } else {
        this.city.parent().parent().addClass(this.errorClassName);
      }
      if (cityVal) {
        $.get('/uu/voip/get-tariff-periods', {
          serviceTypeId: this.voipServiceTypeIdVal,
          currency: this.currencyVal,
          cityId: cityVal,
          isWithEmpty: 1,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.tariffPeriod.val('').html(html);
            return _this.tariffPeriod.trigger('change');
          };
        })(this));
        $.get('/uu/voip/get-tariff-periods', {
          serviceTypeId: this.voipPackageServiceTypeIdVal,
          currency: this.currencyVal,
          cityId: cityVal,
          isWithEmpty: 0,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.packageTariffPeriod.html(html);
            return _this.packageTariffPeriod.trigger('change');
          };
        })(this));
      }
      if (cityVal && numberTypeVal === 'number') {
        return $.get('/uu/voip/get-did-groups', {
          cityId: cityVal,
          isWithEmpty: true,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.didGroup.html(html);
            _this.didGroup.prop('disabled', false);
            return _this.didGroup.val('').trigger('change');
          };
        })(this));
      } else {
        this.didGroup.prop('disabled', true);
        return this.didGroup.val('').trigger('change');
      }
    };

    AccounttariffEdit.prototype.showNumbersList = function() {
      var cityVal, didGroupVal, numberTypeVal;
      numberTypeVal = this.numberType.val();
      cityVal = this.city.val();
      didGroupVal = this.didGroup.val();
      if (cityVal && numberTypeVal === 'number') {
        this.numbersListFilter.slideDown();
      } else {
        this.numbersListFilter.slideUp();
      }
      if (cityVal) {
        this.numbersList.html('');
        return $.get('/uu/voip/get-free-numbers', {
          cityId: cityVal,
          didGroupId: didGroupVal,
          rowClass: this.numbersListClass.val(),
          orderByField: this.numbersListOrderByField.val(),
          orderByType: this.numbersListOrderByType.val(),
          mask: this.numbersListMask.val(),
          limit: this.numbersListLimit.val(),
          numberType: numberTypeVal
        }, (function(_this) {
          return function(html) {
            _this.numbersList.html(html);
            if (_this.numbersList.find('input').length > 1) {
              _this.numbersListSelectAll.show();
            } else {
              _this.numbersListSelectAll.hide();
            }
            return _this.showTariffDiv();
          };
        })(this));
      } else {
        this.numbersList.html('');
        this.numbersListSelectAll.hide();
        return this.showTariffDiv();
      }
    };

    AccounttariffEdit.prototype.selectAllNumbers = function() {
      var isChecked;
      isChecked = this.numbersListSelectAllCheckbox.is(':checked');
      this.numbersList.find('input').prop('checked', isChecked);
      return this.showTariffDiv();
    };

    AccounttariffEdit.prototype.showTariffDiv = function() {
      this.tariffPeriod.trigger('change');
      if (this.numbersList.find('input:checked').length) {
        this.numbersList.removeClass(this.errorClassName);
        return this.tariffDiv.slideDown();
      } else {
        if (this.numbersList.html()) {
          this.numbersList.addClass(this.errorClassName);
        } else {
          this.numbersList.removeClass(this.errorClassName);
        }
        return this.tariffDiv.slideUp();
      }
    };

    AccounttariffEdit.prototype.onTariffPeriodChange = function() {
      if (this.tariffPeriod.val()) {
        return this.tariffPeriod.parent().parent().removeClass(this.errorClassName);
      } else {
        return this.tariffPeriod.parent().parent().addClass(this.errorClassName);
      }
    };

    AccounttariffEdit.prototype.onFormSubmit = function(e) {
      if (!this.tariffPeriod.val()) {
        e.stopPropagation();
        return e.preventDefault();
      }
    };

    return AccounttariffEdit;

  })();

  new AccounttariffEdit();

}).call(this);
