// Generated by CoffeeScript 1.12.2
(function() {
  var AccountTariffEdit,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  AccountTariffEdit = (function() {
    AccountTariffEdit.prototype.country = null;

    AccountTariffEdit.prototype.ndcType = null;

    AccountTariffEdit.prototype.city = null;

    AccountTariffEdit.prototype.didGroup = null;

    AccountTariffEdit.prototype.numbersList = null;

    AccountTariffEdit.prototype.numbersListSelectAll = null;

    AccountTariffEdit.prototype.numbersListSelectAllCheckbox = null;

    AccountTariffEdit.prototype.numbersListFilter = null;

    AccountTariffEdit.prototype.numbersListClass = null;

    AccountTariffEdit.prototype.numbersListOrderByField = null;

    AccountTariffEdit.prototype.numbersListOrderByType = null;

    AccountTariffEdit.prototype.numbersListMask = null;

    AccountTariffEdit.prototype.numbersListLimit = null;

    AccountTariffEdit.prototype.tariffDiv = null;

    AccountTariffEdit.prototype.tariffPeriod = null;

    AccountTariffEdit.prototype.voipServiceTypeIdVal = null;

    AccountTariffEdit.prototype.currencyVal = null;

    AccountTariffEdit.prototype.isPostpaid = null;

    AccountTariffEdit.prototype.errorClassName = 'alert-danger';

    AccountTariffEdit.prototype.successClassName = 'alert-success';

    function AccountTariffEdit() {
      this.onFormSubmit = bind(this.onFormSubmit, this);
      this.reloadTariffList = bind(this.reloadTariffList, this);
      this.onTariffPeriodChange = bind(this.onTariffPeriodChange, this);
      this.showTariffDiv = bind(this.showTariffDiv, this);
      this.selectAllNumbers = bind(this.selectAllNumbers, this);
      this.showNumbersList = bind(this.showNumbersList, this);
      this.onCityChange = bind(this.onCityChange, this);
      this.initCountry = bind(this.initCountry, this);
      this.onCountryChange = bind(this.onCountryChange, this);
      setTimeout((function(_this) {
        return function() {
          _this.country = $('#voipCountryId').on('change', _this.onCountryChange);
          _this.ndcType = $('#voipNdcType').on('change', _this.onCityChange);
          _this.city = $('#voipRegions').on('change', _this.onCityChange);
          _this.didGroup = $('#voipDidGroup').on('change', _this.showNumbersList);
          _this.numbersList = $('#voipNumbersList').on('change', 'input', _this.showTariffDiv);
          _this.numbersListSelectAll = $('#voipNumbersListSelectAll');
          _this.numbersListSelectAllCheckbox = _this.numbersListSelectAll.find('input').on('change', _this.selectAllNumbers);
          _this.numbersListFilter = $('#voipNumbersListFilter');
          _this.tariffDiv = $('#voipTariffDiv');
          _this.numbersListClass = $('#voipNumbersListClass').on('change', _this.showNumbersList);
          _this.numbersListOrderByField = $('#voipNumbersListOrderByField').on('change', _this.showNumbersList);
          _this.numbersListOrderByType = $('#voipNumbersListOrderByType').on('change', _this.showNumbersList);
          _this.numbersListMask = $('#voipNumbersListMask').on('change', _this.showNumbersList);
          _this.numbersListLimit = $('#voipNumbersListLimit').on('change', _this.showNumbersList);
          _this.tariffPeriod = $('.accountTariffTariffPeriod').on('change', _this.onTariffPeriodChange);
          _this.voipServiceTypeIdVal = $('#voipServiceTypeId').val();
          _this.currencyVal = $('#voipCurrency').val();
          _this.isPostpaid = $('#isPostpaid').val();
          $('#addAccountTariffVoipForm').on('submit', _this.onFormSubmit);
          return _this.initCountry(false);
        };
      })(this), 200);
    }

    AccountTariffEdit.prototype.onCountryChange = function() {
      return this.initCountry(true);
    };

    AccountTariffEdit.prototype.initCountry = function(isUpdateCities) {
      var countryVal;
      countryVal = this.country.val();
      if (countryVal) {
        if (isUpdateCities) {
          $.get('/uu/voip/get-cities', {
            countryId: countryVal,
            isWithEmpty: 1,
            format: 'options'
          }, (function(_this) {
            return function(html) {
              _this.city.html(html);
              return _this.city.val('').trigger('change');
            };
          })(this));
        }
        this.country.parent().parent().removeClass(this.errorClassName);
        return this.city.prop('disabled', false);
      } else {
        this.city.prop('disabled', true);
        this.city.val('').trigger('change');
        return this.country.parent().parent().addClass(this.errorClassName);
      }
    };

    AccountTariffEdit.prototype.onCityChange = function() {
      var cityId, ndcTypeId;
      cityId = this.city.val();
      ndcTypeId = this.ndcType.val();
      if (this.city.prop('disabled') || cityId) {
        this.city.parent().parent().removeClass(this.errorClassName);
      } else {
        this.city.parent().parent().addClass(this.errorClassName);
      }
      if (cityId) {
        this.reloadTariffList();
      }
      if (cityId && ndcTypeId >= 0) {
        return $.get('/uu/voip/get-did-groups', {
          cityId: cityId,
          isWithEmpty: 1,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.didGroup.html(html);
            _this.didGroup.prop('disabled', false);
            return _this.didGroup.val('').trigger('change');
          };
        })(this));
      } else {
        this.didGroup.prop('disabled', true);
        return this.didGroup.val('').trigger('change');
      }
    };

    AccountTariffEdit.prototype.showNumbersList = function() {
      var cityId, didGroupVal, ndcTypeId;
      ndcTypeId = this.ndcType.val();
      cityId = this.city.val();
      didGroupVal = this.didGroup.val();
      if (cityId && ndcTypeId >= 0) {
        this.numbersListFilter.slideDown();
      } else {
        this.numbersListFilter.slideUp();
      }
      if (cityId) {
        this.numbersList.html('');
        return $.get('/uu/voip/get-free-numbers', {
          cityId: cityId,
          didGroupId: didGroupVal,
          rowClass: this.numbersListClass.val(),
          orderByField: this.numbersListOrderByField.val(),
          orderByType: this.numbersListOrderByType.val(),
          mask: this.numbersListMask.val(),
          limit: this.numbersListLimit.val(),
          ndcTypeId: ndcTypeId
        }, (function(_this) {
          return function(html) {
            _this.numbersList.html(html);
            if (_this.numbersList.find('input').length > 1) {
              _this.numbersListSelectAll.show();
            } else {
              _this.numbersListSelectAll.hide();
            }
            return _this.showTariffDiv();
          };
        })(this));
      } else {
        this.numbersList.html('');
        this.numbersListSelectAll.hide();
        return this.showTariffDiv();
      }
    };

    AccountTariffEdit.prototype.selectAllNumbers = function() {
      var isChecked;
      isChecked = this.numbersListSelectAllCheckbox.is(':checked');
      this.numbersList.find('input').prop('checked', isChecked);
      return this.showTariffDiv();
    };

    AccountTariffEdit.prototype.showTariffDiv = function() {
      this.tariffPeriod.trigger('change');
      if (this.numbersList.find('input:checked').length) {
        this.numbersList.removeClass(this.errorClassName);
        return this.tariffDiv.slideDown();
      } else {
        if (this.numbersList.html()) {
          this.numbersList.addClass(this.errorClassName);
        } else {
          this.numbersList.removeClass(this.errorClassName);
        }
        return this.tariffDiv.slideUp();
      }
    };

    AccountTariffEdit.prototype.onTariffPeriodChange = function() {
      if (this.tariffPeriod.val()) {
        return this.tariffPeriod.parent().parent().removeClass(this.errorClassName);
      } else {
        return this.tariffPeriod.parent().parent().addClass(this.errorClassName);
      }
    };

    AccountTariffEdit.prototype.reloadTariffList = function() {
      var cityId;
      cityId = this.city.val();
      return $.get('/uu/voip/get-tariff-periods', {
        serviceTypeId: this.voipServiceTypeIdVal,
        currency: this.currencyVal,
        cityId: cityId,
        isWithEmpty: 1,
        format: 'options',
        isPostpaid: this.isPostpaid
      }, (function(_this) {
        return function(html) {
          _this.tariffPeriod.val('').html(html);
          return _this.tariffPeriod.trigger('change');
        };
      })(this));
    };

    AccountTariffEdit.prototype.onFormSubmit = function(e) {
      if (!this.tariffPeriod.val()) {
        e.stopPropagation();
        return e.preventDefault();
      }
    };

    return AccountTariffEdit;

  })();

  new AccountTariffEdit();

}).call(this);
