// Generated by CoffeeScript 1.10.0
(function() {
  var AccounttariffEdit,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  AccounttariffEdit = (function() {
    var country, didGroup, numberType, numbersList, numbersListClass, numbersListMask, numbersListOrderByField, numbersListOrderByType, numbersListSelectAll, regions;

    country = null;

    numberType = null;

    regions = null;

    didGroup = null;

    numbersList = null;

    numbersListSelectAll = null;

    numbersListClass = null;

    numbersListOrderByField = null;

    numbersListOrderByType = null;

    numbersListMask = null;

    function AccounttariffEdit() {
      this.selectAllNumbers = bind(this.selectAllNumbers, this);
      this.showNumbersList = bind(this.showNumbersList, this);
      this.onNumberTypeOrRegionsChange = bind(this.onNumberTypeOrRegionsChange, this);
      this.onCountryChange = bind(this.onCountryChange, this);
      setTimeout((function(_this) {
        return function() {
          _this.country = $('#voipCountryId').on('change', _this.onCountryChange);
          _this.numberType = $('#voipNumberType');
          _this.regions = $('#voipRegions').on('change', _this.onNumberTypeOrRegionsChange);
          _this.didGroup = $('#voipDidGroup').on('change', _this.showNumbersList);
          _this.numbersList = $('#voipNumbersList');
          _this.numbersListSelectAll = $('#voipNumbersListSelectAll input').on('change', _this.selectAllNumbers);
          _this.numbersListClass = $('#voipNumbersListClass').on('change', _this.showNumbersList);
          _this.numbersListOrderByField = $('#voipNumbersListOrderByField').on('change', _this.showNumbersList);
          _this.numbersListOrderByType = $('#voipNumbersListOrderByType').on('change', _this.showNumbersList);
          return _this.numbersListMask = $('#voipNumbersListMask').on('change', _this.showNumbersList);
        };
      })(this), 200);
    }

    AccounttariffEdit.prototype.onCountryChange = function() {
      var countryVal;
      countryVal = this.country.val();
      if (countryVal) {
        $.get('/uu/voip/get-number-types', {
          countryId: countryVal,
          isWithEmpty: true,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.numberType.html(html);
            _this.numberType.prop("disabled", false);
            return _this.numberType.val('').trigger('change');
          };
        })(this));
        return $.get('/uu/voip/get-cities', {
          countryId: countryVal,
          isWithEmpty: true,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.regions.html(html);
            _this.regions.prop("disabled", false);
            return _this.regions.val('').trigger('change');
          };
        })(this));
      } else {
        this.numberType.prop("disabled", true);
        this.numberType.val('').trigger('change');
        this.regions.prop("disabled", true);
        return this.regions.val('').trigger('change');
      }
    };

    AccounttariffEdit.prototype.onNumberTypeOrRegionsChange = function() {
      var regionsVal;
      regionsVal = this.regions.val();
      if (regionsVal) {
        $.get('/uu/voip/get-did-groups', {
          cityId: regionsVal,
          isWithEmpty: true,
          format: 'options'
        }, (function(_this) {
          return function(html) {
            _this.didGroup.html(html);
            _this.didGroup.prop("disabled", false);
            return _this.didGroup.val('').trigger('change');
          };
        })(this));
      } else {
        this.didGroup.prop("disabled", true);
        this.didGroup.val('').trigger('change');
      }
      return this.showNumbersList();
    };

    AccounttariffEdit.prototype.showNumbersList = function() {
      var didGroupVal, regionsVal;
      regionsVal = this.regions.val();
      didGroupVal = this.didGroup.val();
      if (regionsVal) {
        return $.get('/uu/voip/get-free-numbers', {
          cityId: regionsVal,
          didGroupId: didGroupVal,
          rowClass: this.numbersListClass.val(),
          orderByField: this.numbersListOrderByField.val(),
          orderByType: this.numbersListOrderByType.val(),
          mask: this.numbersListMask.val()
        }, (function(_this) {
          return function(html) {
            return _this.numbersList.html(html);
          };
        })(this));
      } else {
        return this.numbersList.html('');
      }
    };

    AccounttariffEdit.prototype.selectAllNumbers = function() {
      var isChecked;
      isChecked = this.numbersListSelectAll.is(':checked');
      return this.numbersList.find('input').prop('checked', isChecked);
    };

    return AccounttariffEdit;

  })();

  new AccounttariffEdit();

}).call(this);
