{{ $_ := set . "redis_server" .Values.redis_server_dev }}

{{- if (eq (env "ENVNAME") "prod") }}
  {{ $_ := set . "redis_server" .Values.redis_server_prod }}
{{ end }}

{{ if eq (int .redis_server.is_standalone) 0 }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  serviceName: redis-db
  replicas: {{ .redis_server.replicas }}
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "podAntiAffinity": {
              "preferredDuringSchedulingIgnoredDuringExecution": [{
                "labelSelector": {
                  "matchExpressions": [{
                    "key": "app",
                    "operator": "In",
                    "values": ["redis-server"]
                  }]
                },
                "topologyKey": "kubernetes.io/hostname"
              }]
            }
          }
    spec:
      initContainers:
      - name: config
        image: redis:6.2.3-alpine
        command: [ "sh", "-c" ]
        args:
          - |
            cp /tmp/redis/redis.conf /etc/redis/redis.conf

            echo "finding master..."
            MASTER_FDQN=`hostname  -f | sed -e 's/redis-server-[0-9]\./redis-server-0./'`
            if [ "$(redis-cli -h redis-sentinel -p 5000 ping)" != "PONG" ]; then
              echo "master not found, defaulting to redis-server-0"
              if [ "$(hostname)" == "redis-server-0" ]; then
                echo "this is redis-server-0, not updating config..."
              else
                echo "updating redis.conf..."
                echo "slaveof $MASTER_FDQN 6379" >> /etc/redis/redis.conf
              fi
            else
              echo "sentinel found, finding master"
              MASTER="$(redis-cli -h redis-sentinel -p 5000 sentinel get-master-addr-by-name mymaster | grep -E '(^redis-server-\d{1,})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})')"
              echo "master found : $MASTER, updating redis.conf"
              echo "slaveof $MASTER 6379" >> /etc/redis/redis.conf
            fi      
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: config
          mountPath: /tmp/redis/          
      containers:            
      - name: redis-server
        image: redis:6.2.2-alpine
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/
      volumes:
      - name: redis-config
        emptyDir: {}
      - name: config
        configMap:
          name: redis-config
      - name: data
        emptyDir: {}
#  volumeClaimTemplates:
#  - metadata:
#      name: data
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: "standard"
#      resources:
#        requests:
#          storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-db
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis-server
{{ end }}
