{{ $_ := set . "env" (printf "%s-%s-%s" .Chart.Name (env "ENVNAME" | lower) (env "COUNTRY" | lower)) }}
{{ if eq (env "IS_WITH_MAILER") "1" }}

{{ if and (eq (env "IS_MINIKUBE") "1") (eq (env "COUNTRY") "RU") }}
  {{/* $_ := set . "mysql" .Values.mysql_prod_readonly */}}
  {{ $_ := set . "mysql" .Values.mysql_dev }}
{{ else }}
  {{ $_ := set . "mysql" (ternary .Values.mysql_prod_eu .Values.mysql_prod (eq (env "COUNTRY") "EU")) }}
{{ end }}

{{ $_ := set . "params" .Values.params_dev }}

{{- if (eq (env "ENVNAME") "prod") }}
  {{ $_ := set . "params" (ternary .Values.params_prod_eu .Values.params_prod (eq (env "COUNTRY") "EU")) }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mailer-configs
data:
  db.local.php: |
    <?php
      return [
        'class' => 'yii\db\Connection',
        'dsn' => 'mysql:host={{ .mysql.host }};port={{ .mysql.port }};dbname=mailer',
        'username' => '{{ .mysql.user }}',  
        'password' => '{{ .mysql.password }}',
        'charset' => 'utf8',
    ]; 

  params.local.php: |
    <?php
    return [
      'stat_api' => [
        'host' => 'http://{{ printf "%s-backend-%s-%s.%s-%s" .Chart.Name ((env "ENVNAME") | lower) ((env "COUNTRY") | lower) .Chart.Name  ((env "ENVNAME") | lower) }}/',  // Полный URL до Stat API
        'uri' => '/api/',  // Полный URL до Stat API
        'auth' => [
          'method' => 'bearer',  // basic: BasicAuth, bearer: AuthorizationBearer
          'token' => '{{ .params.api_secure_key }}',
        ],
      ],
      'smser' => [
        'url' => '{{ .params.sms_gate.server }}',
        'client' => '{{ .params.sms_gate.client }}',
        'password' => '{{ .params.sms_gate.password }}',
      ],
      'from' => [
        'ru-RU' => 'noreply@mcn.ru',
        'hu-HU' => 'noreply@kompaas.tech',
        'en-EN' => 'noreply@kompaas.tech',
        'de-DE' => 'noreply@kompaas.tech',
        'sk-SK' => 'noreply@kompaas.tech',
      ],
      'system_addresses'=> [
        'monitoring' => 'monitoring@mcn.ru',
        'operator' => 'oper@mcn.ru',
      ],
    ];

  log.local.php: |
    <?php
    $graylogHost = 'graylogstat.mcn.ru';
    $source = 'mailer';

    {{ if eq (env "COUNTRY") "RU" }}
   
    return [
      'traceLevel' => 0,
      'flushInterval' => 1,
      'targets' => [
        [
          'exportInterval' => 1,
          'class' => 'welltime\graylog\GraylogTarget',
          'levels' => ['info'],
          'categories' => ['application'],
          'host' => $graylogHost,
          'source' => $source,
        ],
        [
          'exportInterval' => 1,
          'class' => 'welltime\graylog\GraylogTarget',
          'levels' => ['error', 'warning'],
          'host' => $graylogHost,
          'source' => $source,
        ],
        [
          'exportInterval' => 3,
          'class' => 'yii\log\FileTarget',
          'levels' => ['info', 'error', 'warning'],
          'logFile' => '/tmp/mailer.log',
          'logVars' => [],
        ],
      ],
    ];
    
    {{ else }}
        
    return [
      'traceLevel' => 0,
      // disable/downgrade for php7.1 // 'class' => 'yii\log\Logger',
      'flushInterval' => 3,
      'targets' => [
        [ 
          'exportInterval' => 3,
          'class' => 'yii\log\FileTarget',
          'levels' => ['info', 'error', 'warning'],
          'logFile' => '/tmp/mailer.log',
          'logVars' => [],
        ],
      ],
    ];
    
    {{ end }}

  mailer.local.php: |
    <?php
    return [
      'class' => 'yii\swiftmailer\Mailer',
      'viewPath' => '@app/mail',
      'transport' => [
        'class' => 'Swift_SmtpTransport',
        'host' => '{{ .params.mailer.smtp.server }}',
        'port' => '25',  // '587',
        // 'encryption' => 'tls',
      ],
    ];
    

  crontab.file: |
    * * * * * cd /app/mailer; flock -x /var/run/mailer.lock ./yii mail/mail >> /tmp/mailer.log

  empty: |
    empty

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mailer-nginx-templates
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 0.0.0.0:80 default_server;
        ### listen [::]:80 default_server;
      
        # Set nginx to serve files from the shared volume!
        root /app/mailer/web/;
        index index.php
        server_name mailer.mcn.local;
        charset utf-8;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        location = /ping {
          add_header Content-Type text/plain;
          return 200 "Pong\n";
        }
        location / {
          #try_files $uri $uri/ =404;
          #try_files $uri $uri/ /index.php?$args;
          try_files $uri $uri/ /index.php$is_args$args;
        }
        location ~ \.php$ {
          include fastcgi_params;
          #fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_read_timeout 10h;
          try_files $uri =404;
        }
      }
    }

  php-fpm.conf: |
    ; /usr/local/etc/php-fpm.d/try-debug.conf
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 256
    pm.start_servers = 5
    pm.min_spare_servers = 5
    pm.max_spare_servers = 35
    pm.max_requests = 1000
    slowlog = /var/log/php-fpm-slow.log
    ;
    pm.status_path = /site-status
    ping.path = /site-ping
    ping.response = Site-pong
    ;
    
    access.log = /var/log/$pool.access.log

  tmp.tmp: |
    tmp.tmp

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mailer-processor-{{ .env }}
  labels:
    app: {{ .Chart.Name }}-mailer-{{ .env }}
spec:
  replicas: 1
  # revisionHistoryLimit: 3
  serviceName: mailer-processor-service-{{ .env }}
  selector:
    matchLabels:
      service: mailer-processor-{{ .env }}
  template:
    metadata:
      labels:
        service: mailer-processor-{{ .env }}
    spec:
      containers:
        - name: fpm
{{ tuple (printf "%s-mailer-php-fpm-%s"  .Chart.Name (env "ENVNAME")) . | werf_container_image | indent 10 }}
          env:
            - name: LC_ALL
              value: en_US.UTF-8
          ports:
            - containerPort: 9000
              name: php-fpm
              protocol: TCP
            - containerPort: 9001
              name: yii-serve
              protocol: TCP
          volumeMounts:
            - name: mailer-nginx-templates
              mountPath: /usr/local/etc/php-fpm.d/try-debug.conf
              subPath: php-fpm.conf
            - name: mailer-configs
              mountPath: /tmp/config/
            - name: crontab-dir
              mountPath: /etc/crontabs/

#          command: ["/bin/sh", "-c", "/root/entrypoint.sh"]
# ln -s /dev/stdout /tmp/mailer.log && while :; do sleep 10000; done
          command: [ "/bin/sh" ]
          args:
            - -c
            - >
              cp /tmp/config/*.php /app/mailer/config/ &&
              cp /tmp/config/crontab.file /etc/crontabs/root && 
              chmod 0600 /etc/crontabs/root &&
              crond &&
              /usr/local/sbin/php-fpm -D &&
              touch /tmp/mailer.log && 
              tail -f /tmp/mailer.log | grep '\[-\]' | grep -v '_SERVER'

        - name: nginx
{{ tuple (printf "%s-mailer-nginx-%s"  .Chart.Name (env "ENVNAME")) . | werf_container_image | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mailer-nginx-templates
#              mountPath: /etc/nginx/templates
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
              name: nginx-mailer
              protocol: TCP
          command: [ "nginx", "-g", "daemon off;" ]

      volumes:
        - name: mailer-nginx-templates
          configMap:
            name: {{ .Chart.Name }}-mailer-nginx-templates
        - name: mailer-processor-config-volume
          configMap:
            name: {{ .Chart.Name }}-mailer-processor-config
        - name: mailer-configs
          configMap:
            name: {{ .Chart.Name }}-mailer-configs
        - name: crontab-dir
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mailer-processor-service-{{ .env }}
  labels:
    app: {{ .Chart.Name }}-mailer-{{ .env }}
spec:
  selector:
    service: mailer-processor-{{ .env }}
  ports:
    - name: mailer-web-http
      port: 80
      protocol: TCP
    - name: mailer-php-fpm
      port: 9000
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-mailer-{{ .env }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: mailer.mcn.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mailer-processor-service-{{ .env }}
                port:
                  number: 80
{{- end }}
