<?php

use app\models\ClientContractType;
use app\models\ClientBPStatuses;
use app\models\ClientGridBussinesProcess;

return [

    37 => [
        'id' => 37,
        'name' => \Yii::t('app', 'Входящий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_INCOMMING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'income',
        'color' => '#CCFFFF',
    ],
    38 => [
        'id' => 38,
        'name' => \Yii::t('app', 'Переговоры'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'negotiations',
        'color' => '#C4DF9B',
    ],
    39 => [
        'id' => 39,
        'name' => \Yii::t('app', 'Тестирование'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_TESTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'testing',
        'color' => '#6DCFF6',
    ],
    40 => [
        'id' => 40,
        'name' => \Yii::t('app', 'Действующий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_ACTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'work',
        'color' => '',
    ],
    107 => [
        'id' => 107,
        'name' => \Yii::t('app', 'Ручной счет'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_MANUAL_BILL],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '#CCFFFF',
    ],
    41 => [
        'id' => 41,
        'name' => \Yii::t('app', 'Приостановлен'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_SUSPENDED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'suspended',
        'color' => '#C4a3C0',
    ],
    42 => [
        'id' => 42,
        'name' => \Yii::t('app', 'Расторгнут'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_TERMINATED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'closed',
        'color' => '#FFFFCC',
    ],
    43 => [
        'id' => 43,
        'name' => \Yii::t('app', 'Фрод блокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_BLOCKED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'blocked',
        'color' => 'silver',
    ],
    44 => [
        'id' => 44,
        'name' => \Yii::t('app', 'Техотказ'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_TECH_FAILURE],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'tech_deny',
        'color' => '#996666',
    ],
    45 => [
        'id' => 45,
        'name' => \Yii::t('app', 'Автоблокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_OPERATORS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_OPERATORS_AUTO_BLOCKED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],
    47 => [
        'id' => 47,
        'name' => \Yii::t('app', 'Входящий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_INCOMMING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'income',
        'color' => '#CCFFFF',
    ],
    48 => [
        'id' => 48,
        'name' => \Yii::t('app', 'Переговоры'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'negotiations',
        'color' => '#C4DF9B',
    ],
    49 => [
        'id' => 49,
        'name' => \Yii::t('app', 'Тестирование'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_TESTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'testing',
        'color' => '#6DCFF6',
    ],
    50 => [
        'id' => 50,
        'name' => \Yii::t('app', 'Действующий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_ACTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'work',
        'color' => '',
    ],
    51 => [
        'id' => 51,
        'name' => \Yii::t('app', 'Приостановлен'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_SUSPENDED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'suspended',
        'color' => '#C4a3C0',
    ],
    52 => [
        'id' => 52,
        'name' => \Yii::t('app', 'Расторгнут'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_TERMINATED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'closed',
        'color' => '#FFFFCC',
    ],
    53 => [
        'id' => 53,
        'name' => \Yii::t('app', 'Фрод блокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_BLOCKED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'blocked',
        'color' => 'silver',
    ],
    54 => [
        'id' => 54,
        'name' => \Yii::t('app', 'Техотказ'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_CLIENTS_TECH_FAILURE],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'tech_deny',
        'color' => '#996666',
    ],
    55 => [
        'id' => 55,
        'name' => \Yii::t('app', 'Автоблокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_CLIENTS,
        'queryParams' => [
            'where' => [
                ['!=', 'cr.business_process_status_id', ClientBPStatuses::STATE_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],
    62 => [
        'id' => 62,
        'name' => \Yii::t('app', 'Входящий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_INCOMMING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'income',
        'color' => '#CCFFFF',
    ],
    63 => [
        'id' => 63,
        'name' => \Yii::t('app', 'Переговоры'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'negotiations',
        'color' => '#C4DF9B',
    ],
    64 => [
        'id' => 64,
        'name' => \Yii::t('app', 'Тестирование'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_TESTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'testing',
        'color' => '#6DCFF6',
    ],
    65 => [
        'id' => 65,
        'name' => \Yii::t('app', 'Действующий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_ACTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'work',
        'color' => '',
    ],
    66 => [
        'id' => 66,
        'name' => \Yii::t('app', 'Приостановлен'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_SUSPENDED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'suspended',
        'color' => '#C4a3C0',
    ],
    67 => [
        'id' => 67,
        'name' => \Yii::t('app', 'Расторгнут'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_TERMINATED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'closed',
        'color' => '#FFFFCC',
    ],
    68 => [
        'id' => 68,
        'name' => \Yii::t('app', 'Фрод блокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_BLOCKED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'blocked',
        'color' => 'silver',
    ],
    69 => [
        'id' => 69,
        'name' => \Yii::t('app', 'Техотказ'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_INFRASTRUCTURE_TECH_FAILURE],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'tech_deny',
        'color' => '#996666',
    ],
    70 => [
        'id' => 70,
        'name' => \Yii::t('app', 'Автоблокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_INFRASTRUCTURE,
        'queryParams' => [
            'where' => [
                ['!=', 'cr.business_process_status_id', ClientBPStatuses::STATE_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],
    77 => [
        'id' => 77,
        'name' => \Yii::t('app', 'Входящий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_INCOMMING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'income',
        'color' => '#CCFFFF',
    ],
    78 => [
        'id' => 78,
        'name' => \Yii::t('app', 'Переговоры'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'negotiations',
        'color' => '#C4DF9B',
    ],
    79 => [
        'id' => 79,
        'name' => \Yii::t('app', 'Тестирование'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_TESTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'testing',
        'color' => '#6DCFF6',
    ],
    80 => [
        'id' => 80,
        'name' => \Yii::t('app', 'Действующий'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_ACTING],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'work',
        'color' => '',
    ],
    81 => [
        'id' => 81,
        'name' => \Yii::t('app', 'Приостановлен'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_SUSPENDED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'suspended',
        'color' => '#C4a3C0',
    ],
    82 => [
        'id' => 82,
        'name' => \Yii::t('app', 'Расторгнут'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_TERMINATED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'closed',
        'color' => '#FFFFCC',
    ],
    83 => [
        'id' => 83,
        'name' => \Yii::t('app', 'Фрод блокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_BLOCKED],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'blocked',
        'color' => 'silver',
    ],
    84 => [
        'id' => 84,
        'name' => \Yii::t('app', 'Техотказ'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['cr.business_process_status_id' => ClientBPStatuses::OPERATOR_FORMAL_TECH_FAILURE],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'tech_deny',
        'color' => '#996666',
    ],
    85 => [
        'id' => 85,
        'name' => \Yii::t('app', 'Автоблокировка'),
        'grid_business_process_id' => ClientGridBussinesProcess::OPERATOR_FORMAL,
        'queryParams' => [
            'where' => [
                ['!=', 'cr.business_process_status_id', ClientBPStatuses::STATE_NEGOTIATIONS],
                ['cr.contract_type_id' => ClientContractType::OPERATOR],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],

];