<?php

use app\models\ContractType;
use app\models\BusinessProcessStatus;
use app\models\BusinessProcess;

return [

    19 => [
        'id' => 19,
        'name' => \Yii::t('app', 'Заказ услуг'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_ORDER_OF_SERVICES],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'negotiations',
        'color' => '#C4DF9B',
    ],
    8 => [
        'id' => 8,
        'name' => \Yii::t('app', 'Подключаемые'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_CONNECTED],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'connecting',
        'color' => '#F49AC1',
    ],
    9 => [
        'id' => 9,
        'name' => \Yii::t('app', 'Включенные'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_WORK],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'account_manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => false,
        'oldstatus' => 'work',
        'hideCount' => true,
        'color' => '',
    ],
    10 => [
        'id' => 10,
        'name' => \Yii::t('app', 'Отключенные'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_DISCONNECTED],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'closed',
        'hideCount' => true,
        'color' => '#FFFFCC',
    ],
    11 => [
        'id' => 11,
        'name' => \Yii::t('app', 'Отключенные за долги'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['c.is_blocked' => 1],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_WORK],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            //'block_date',
            'currency',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => 'debt',
        'color' => '#C00000',
    ],
    21 => [
        'id' => 21,
        'name' => \Yii::t('app', 'Автоблокировка'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['c.is_blocked' => 0],
                [
                    'not in',
                    'cr.business_process_status_id',
                    [
                        BusinessProcessStatus::TELEKOM_MAINTENANCE_CONNECTED,
                        BusinessProcessStatus::TELEKOM_MAINTENANCE_DISCONNECTED_DEBT,
                    ],
                ],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'currency',
            //'block_date',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => NULL,
        'color' => '',
    ],
    22 => [
        'id' => 22,
        'name' => \Yii::t('app', 'Мусор'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_TRASH],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'trash',
        'hideCount' => true,
        'color' => '#a5e934',
    ],
    23 => [
        'id' => 23,
        'name' => \Yii::t('app', 'Не привязанные'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_NOT_CONNECTED],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => NULL,
        'color' => '',
    ],
    27 => [
        'id' => 27,
        'name' => \Yii::t('app', 'Техотказ'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_TECH_FAILURE],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'tech_deny',
        'hideCount' => true,
        'color' => '#996666',
    ],
    28 => [
        'id' => 28,
        'name' => \Yii::t('app', 'Отказ'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_FAILURE],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'deny',
        'hideCount' => true,
        'color' => '#A0A0A0',
    ],
    29 => [
        'id' => 29,
        'name' => \Yii::t('app', 'Дубликат'),
        'grid_business_process_id' => BusinessProcess::TELECOM_MAINTENANCE,
        'queryParams' => [
            'where' => [
                ['cr.contract_type_id' => ContractType::TELEKOM],
                ['cr.business_process_status_id' => BusinessProcessStatus::TELEKOM_MAINTENANCE_DUPLICATE],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => true,
        'is_close_status' => true,
        'oldstatus' => 'double',
        'color' => '#60a0e0',
    ],
    1 => [
        'id' => 1,
        'name' => \Yii::t('app', 'Входящие'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['c.status' => 'income'],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => true,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => 'income',
        'color' => '#CCFFFF',
    ],
    2 => [
        'id' => 2,
        'name' => \Yii::t('app', 'В стадии переговоров'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['c.status' => 'negotiations'],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => 'negotiations',
        'color' => '#C4DF9B',
    ],
    3 => [
        'id' => 3,
        'name' => \Yii::t('app', 'Тестируемые'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['c.status' => 'testing'],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => 'testing',
        'color' => '#6DCFF6',
    ],
    4 => [
        'id' => 4,
        'name' => \Yii::t('app', 'Подключаемые'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['c.status' => 'connecting'],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => 'connecting',
        'color' => '#F49AC1',
    ],
    5 => [
        'id' => 5,
        'name' => \Yii::t('app', 'Техотказ'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['c.status' => 'tech_deny'],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => true,
        'oldstatus' => 'tech_deny',
        'hideCount' => true,
        'color' => '#996666',
    ],
    6 => [
        'id' => 6,
        'name' => \Yii::t('app', 'Отказ'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['c.status' => 'deny'],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => true,
        'oldstatus' => 'deny',
        'hideCount' => true,
        'color' => '#A0A0A0',
    ],
    7 => [
        'id' => 7,
        'name' => \Yii::t('app', 'Мусор'),
        'grid_business_process_id' => BusinessProcess::TELECOM_SALES,
        'queryParams' => [
            'where' => [
                ['in', 'c.status', ['double', 'trash']],
                ['cr.contract_type_id' => ContractType::TELEKOM],
            ],
        ],
        'columns' => [
            'status',
            'id',
            'company',
            'created',
            'currency',
            'sale_channel',
            'manager',
            'region',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => true,
        'oldstatus' => 'trash',
        'hideCount' => true,
        'color' => '#a5e934',
    ],
    101 => [
        'id' => 101,
        'name' => \Yii::t('app', 'Доход по клиентам'),
        'grid_business_process_id' => 16,
        'queryParams' => [
            'select' => [
                'l.service',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0,l.sum,0)) AS abon',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11,l.sum,0)) AS over',
                'sum(l.sum) as total',
                'b.bill_date',
            ],
            'join' => [
                [
                    'INNER JOIN',
                    'newbills b',
                    'c.id=b.client_id',
                ],
                [
                    'INNER JOIN',
                    'newbill_lines l',
                    'l.bill_no=b.bill_no',
                ],
            ],
            'where' => [
                'b.is_payed = 1',
                'l.type = "service"',
                [
                    'not in',
                    'l.service',
                    ['1C', 'bill_monthlyadd', '', 'all4net',],
                ],
                'b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND  :date_to',
            ],
            'groupBy' => [
                'l.service',
                'c.id',
            ],
            'orderBy' => [
                'over' => 3,
            ],
            'params' => [
                'date_from' => date('Y-m-01'),
                'date_to' => date('Y-m-t')
            ]
        ],
        'columns' => [
            'id',
            'company',
            'account_manager',
            'manager',
            'region',
            'service',
            'bill_date',
            'abon',
            'over',
            'total',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'hideCount' => true,
        'color' => '',
    ],
    102 => [
        'id' => 102,
        'name' => \Yii::t('app', 'Доход по менеджеру и услугам'),
        'grid_business_process_id' => 16,
        'queryParams' => [
            'select' => [
                'l.service',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0,l.sum,0)) AS abon',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11,l.sum,0)) AS over',
                'sum(l.sum) as total',
                'b.bill_date',
            ],
            'join' => [
                [
                    'INNER JOIN',
                    'newbills b',
                    'c.id=b.client_id',
                ],
                [
                    'INNER JOIN',
                    'newbill_lines l',
                    'l.bill_no=b.bill_no',
                ],
            ],
            'where' => [
                'b.is_payed = 1',
                'l.type = "service"',
                [
                    'not in',
                    'l.service',
                    ['1C', 'bill_monthlyadd', '', 'all4net',],
                ],
                'b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND  :date_to',
            ],
            'groupBy' => [
                'cr.account_manager',
            ],
            'orderBy' => [
                'over' => 3,
            ],
            'params' => [
                'date_from' => date('Y-m-01'),
                'date_to' => date('Y-m-t')
            ]
        ],
        'columns' => [
            'account_manager',
            'service',
            'region',
            'abon',
            'over',
            'total',
            'bill_date',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],
    103 => [
        'id' => 103,
        'name' => \Yii::t('app', 'Доход по менеджеру'),
        'grid_business_process_id' => 16,
        'queryParams' => [
            'select' => [
                'l.service',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0,l.sum,0)) AS abon',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11,l.sum,0)) AS over',
                'sum(l.sum) as total',
                'b.bill_date',
            ],
            'join' => [
                [
                    'INNER JOIN',
                    'newbills b',
                    'c.id=b.client_id',
                ],
                [
                    'INNER JOIN',
                    'newbill_lines l',
                    'l.bill_no=b.bill_no',
                ],
            ],
            'where' => [
                'b.is_payed = 1',
                'l.type = "service"',
                [
                    'not in',
                    'l.service',
                    ['1C', 'bill_monthlyadd', '', 'all4net',],
                ],
                'b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND  :date_to',
            ],
            'groupBy' => [
                'cr.account_manager',
            ],
            'orderBy' => [
                'over' => 3,
            ],
            'params' => [
                'date_from' => date('Y-m-01'),
                'date_to' => date('Y-m-t')
            ]
        ],
        'columns' => [
            'account_manager',
            'region',
            'abon',
            'over',
            'total',
            'bill_date',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],
    104 => [
        'id' => 104,
        'name' => \Yii::t('app', 'Доход по услугам'),
        'grid_business_process_id' => 16,
        'queryParams' => [
            'select' => [
                'l.service',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0,l.sum,0)) AS abon',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11,l.sum,0)) AS over',
                'sum(l.sum) as total',
                'b.bill_date',
            ],
            'join' => [
                [
                    'INNER JOIN',
                    'newbills b',
                    'c.id=b.client_id',
                ],
                [
                    'INNER JOIN',
                    'newbill_lines l',
                    'l.bill_no=b.bill_no',
                ],
            ],
            'where' => [
                'b.is_payed = 1',
                'l.type = "service"',
                [
                    'not in',
                    'l.service',
                    ['1C', 'bill_monthlyadd', '', 'all4net',],
                ],
                'b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND  :date_to',
            ],
            'groupBy' => [
                'l.service',
            ],
            'orderBy' => [
                'over' => 3,
            ],
            'params' => [
                'date_from' => date('Y-m-01'),
                'date_to' => date('Y-m-t')
            ]
        ],
        'columns' => [
            'service',
            'region',
            'abon',
            'over',
            'total',
            'bill_date',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'color' => '',
    ],
    106 => [
        'id' => 106,
        'name' => \Yii::t('app', 'Расхождение'),
        'grid_business_process_id' => 16,
        'queryParams' => [
            'select' => [
                'l.service',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0 AND b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND DATE_ADD( :date_to, INTERVAL -1 MONTH),l.sum,0)) AS abon',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0 AND b.bill_date BETWEEN  :date_from AND  :date_to,l.sum,0)) AS abon1',
                'SUM(IF((MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11) AND b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND DATE_ADD( :date_to, INTERVAL -1 MONTH),l.sum,0)) AS over',
                'SUM(IF((MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11) AND b.bill_date BETWEEN  :date_from AND  :date_to,l.sum,0)) AS over1',
                'SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0 AND b.bill_date BETWEEN  :date_from AND  :date_to,l.sum,0))-SUM(IF(MONTH(l.date_from)-MONTH(b.bill_date)=0 AND b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND DATE_ADD( :date_to, INTERVAL -1 MONTH),l.sum,0)) AS abondiff',
                'SUM(IF((MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11) AND b.bill_date BETWEEN  :date_from AND  :date_to,l.sum,0))-SUM(IF((MONTH(l.date_from)-MONTH(b.bill_date)=-1 OR MONTH(l.date_from)-MONTH(b.bill_date)=11) AND b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND DATE_ADD( :date_to, INTERVAL -1 MONTH),l.sum,0)) As overdiff',
                'b.bill_date',
            ],
            'join' => [
                [
                    'INNER JOIN',
                    'newbills b',
                    'c.id=b.client_id',
                ],
                [
                    'INNER JOIN',
                    'newbill_lines l',
                    'l.bill_no=b.bill_no',
                ],
            ],
            'where' => [
                'l.type = "service"',
                [
                    'not in',
                    'l.service',
                    ['1C', 'bill_monthlyadd', '', 'all4net',],
                ],
                ' b.bill_date BETWEEN DATE_ADD( :date_from, INTERVAL -1 MONTH) AND  :date_to'
            ],
            'groupBy' => [
                'l.service',
                'c.id',
            ],
            'orderBy' => [
                'over' => 3,
            ],
            'params' => [
                'date_from' => date('Y-m-01'),
                'date_to' => date('Y-m-t')
            ]
        ],
        'columns' => [
            'id',
            'company',
            'account_manager',
            'manager',
            'region',
            'service',
            'bill_date',
            'abon',
            'abon1',
            'over',
            'over1',
            'abondiff',
            'overdiff',
        ],
        'default' => false,
        'show_as_status' => false,
        'is_close_status' => false,
        'oldstatus' => null,
        'hideCount' => true,
        'color' => '',
    ],

];